package com.quantcraft.market;

public enum WorldMarketEvent {
    PLAYER_MINED_ORE,
    PLAYER_MINED_WOOD,
    PLAYER_HARVESTED_CROP,
    PLAYER_KILLED_MOB,
    PLAYER_KILLED_BOSS,
    RAID_OCCURRED,
    CLEAR_WEATHER,
    PLAYER_BOUGHT_STOCK,
    PLAYER_SOLD_STOCK,
    ADMIN_SECTOR_CRASH,
    ADMIN_SECTOR_BOOM
}
